{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'css': [],
    'data': [],
    'demo': [],
    'demo_xml': [],
    'depends': ['base'],
    'external_dependencies': {'bin': [], 'python': []},
    'js': [],
    'name': 'zbsync_xport',
    'qweb': [],
    'summary': 'Exports/Imports the connector in json files',
    'test': [],
    'version': '1.1'}
