{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'data': [],
    'demo': [],
    'depends': ['zbsync_mapper', 'zbsync_odoo'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'zbsync_odoo_mapper',
    'qweb': [],
    'test': [],
    'version': '1.0'}
