{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'data': [],
    'demo': [],
    'depends': ['queue_job', 'zbsync'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'zbsync_queuejob',
    'qweb': [],
    'test': [],
    'version': '1.0'}
